meedan/alegre

.gitignore
Dockerfile
Makefile
docker-entrypoint.sh
docker/Dockerfile.production
docker/bin/start.sh
elasticsearch/Dockerfile
requirements.txt
wsgi.py

* Remove nginx from image
* Ensure .env file is loaded wholesale into container, not variable by variable

Streamline deployment

---

app/main/controller/image_similarity_controller.py

But still log the exception... I expect that this way the subsequent requests won't fail.

Ticket #8176: Rollback session in case of exception

---

.gitlab-ci.yml

This change updates the version pins for boto3 and botocore to resolve incompatibilities in ecs deploy.

Update ecs deploy

---

.gitlab-ci.yml

This change uses the SSM parameter store to configure the Alegre task environment using the ecs-deploy utility.

SSM configuration

---

.gitlab-ci.yml
app/main/controller/image_similarity_controller.py
app/main/lib/google_client.py
production/bin/start.sh

This change implements some housekeeping and uses SSM parameter store for populating task environment.

Use exclusive secrets and SSM based configuration

---

.gitlab-ci.yml

Fix typo in ecs deploy command referencing QA container for Live deploy.

Fix typo in ecs deploy command

---

.gitlab-ci.yml
app/main/lib/shared_models/video_model.py
threatexchange/tmk/cpp/hashing/filehasher.cpp

This change suppresses notification and debug messages when TMK invokes ffmpeg. Greatly reduces CloudWatch log activity.

Sssh ffmpeg

---

.gitlab-ci.yml

This change deploys a new alegre-audio task for the new audio similarity model in QA and Live environments.

Deploy audio model

---

.gitlab-ci.yml

This merge restores missing deploy commands for video, indiansbert, and meantokens models in the QA environment.

Deploy all models to QA

---

app/main/controller/audio_similarity_controller.py
app/main/controller/image_similarity_controller.py
app/main/controller/similarity_controller.py
app/main/controller/video_similarity_controller.py

CHECK-2284 update documentation to more explicitly call out that swagger docs wont work out of box

---

app/main/lib/image_similarity.py

Rather than just 'image', return `image/specific_model` i.e., `image/phash`, `image/pdq` or `image/context`

CV2-1002 Update image model name with specific model

---

app/main/lib/shared_models/video_model.py

https://meedan.atlassian.net/browse/CV2-3249

[CV2-3249] track error

---

app/main/controller/audio_transcription_controller.py
app/test/test_audio_transcription.py

Minor ticket to add a new, known, normal, error type.
Reference: CV2-3577
No new tests for this case yet - I can add if it seems reasonable?

CV2-3577 add unsupported audio format to list of known error states

---

pull_request_template.md

This is a bit self-referential; however this change adds security considerations to the pull request template as discussed in today's retrospective. :)

Add security considerations to pull request template.

---

app/main/lib/shared_models/paraphrase_multilingual_mpnet_base_v2.py
docker-compose.yml
elasticsearch/alegre_similarity.json
model_config.json

Reference: ticket id CV2-3482
Locally and integration tests

adding support to paraphrase-multilingual-mpnet-base-v2

---

.gitlab-ci.yml

This fix updates version pins for python packages awscli, boto3, botocore, and ecs-deploy to fix deployments.
Reference: https://meedan.atlassian.net/browse/DEVOPS-502
I verified this build and deployment process in QA.
Yes :)

Update version pins for Python dependencies to fix deployments.

---

app/main/controller/article_controller.py
app/main/controller/audio_similarity_controller.py
app/main/controller/audio_transcription_controller.py
app/main/controller/image_classification_controller.py
app/main/controller/image_ocr_controller.py
app/main/controller/image_similarity_controller.py
app/main/controller/langid_controller.py
app/main/controller/presto_controller.py
app/main/controller/similarity_async_controller.py
app/main/controller/similarity_controller.py
app/main/controller/similarity_sync_controller.py
app/main/controller/translation_controller.py
app/main/controller/video_similarity_controller.py
app/main/lib/shared_models/audio_model.py
app/main/lib/shared_models/video_model.py
app/main/lib/text_similarity.py
app/test/pact/check_api-alegre.json
app/test/test_article.py
app/test/test_async_similarity.py
app/test/test_audio_transcription.py
app/test/test_image_classification.py
app/test/test_image_similarity.py
app/test/test_langid.py
app/test/test_ocr.py
app/test/test_similarity.py
app/test/test_similarity_lang_analyzers.py
app/test/test_sync_similarity.py
app/test/test_translation.py
app/test/test_video_similarity.py

we send JSON data in bodies to GET requests. We can't contract test that. It's non standard. We are all over the place in terms of how we accept input. I am fixing that.
Reference: 3828
This will affect ≈ 100 checks across unit tests, so will be heavily tested by the end.

Cv2 3828 audio update

---

app/main/lib/shared_models/audio_model.py

Small tweak - misread logic on previous PR
Reference: 3828
Run via QA and confirmed to solve:
```
>>> import json
>>> args = json.loads('{"doc_id":"Y2hlY2stcHJvamVjdF9tZWRpYS0yMzI4NC0","context":{"team_id":196,"project_media_id":23284,"has_custom_id":true},"url":"https://qa-assets.checkmedia.org/uploads/uploaded_audio/47134/a1bdc48c961fe3a05b11cea6e2d4b2c3.mp3","threshold":0.9}')
>>> similarity_type = "audio"
>>> import json
>>> from flask import request, current_app as app
>>> from flask_restplus import Resource, Namespace, fields
>>> 
>>> from app.main.lib.fields import JsonObject
>>> from app.main.lib import similarity
>>> 
>>> 
>>> package = similarity.get_body_for_media_document(args, 'query')
INFO:flask.app:[Alegre Similarity] get_body_for_text_document (mode=query):params (start) …
```

should be an if

---

app/main/lib/media_crud.py
app/test/test_media_crud.py

Fixes 4102
Tested on production, lol, it works for this case that is causing the issue that we observed in sentry

add better merger for contexts

---

app/main/model/image.py
manage.py
migrations/versions/5e823fb0eaaa_create_sscd_column.py
postgres/Dockerfile
requirements.txt

Implementing SSCD-copy-detection algorithm. 
Reference: Cv2 3700
Tested locally, to be tested in the PR by automated and integration tests
no security concerns found

Cv2 3700 sscd image similarity algorithm

---

production/bin/start.sh

This change adds more worker capacity for proper utilization of ECS resources.
This has been sanity checked in QA.
Yes, and additional care will be taken to observe performance with this configuration under load.

Increase gunicorn server settings for more performance.

---

app/main/lib/image_similarity.py
app/main/lib/shared_models/audio_model.py
app/test/test_sync_similarity.py

Reference: TICKET-ID (to provide additional context)

Cv2 4136 yake model

---

app/main/lib/shared_models/video_model.py
app/test/test_video_similarity.py

Just some minor fixes after merging video

remove stray error logs that were just used for printouts

---

app/main/lib/image_similarity.py
app/main/lib/media_crud.py
app/test/test_media_crud.py

God willing some of the last fixes on 4126
Not tested locally because it's in a complicated path, but this aligns this path with sync requests, which was working.
None

CV2-4126 ensure context is appended in async branch to existing items, strictly prefer doc id over url, unnest logic

---

app/main/lib/image_similarity.py

Lookups dont work when looking for cached version because of package mismatch

CV2-4126 Lookup for both flows, if cached or not cached version

---

production/bin/start.sh

Better tuning for workers to reduce memory pressure and better utilize resources.
Reference: CV2-4429.
Empirical estimation :)
No security concerns.

Tune worker count based on better resource estimation. See CV2-4429.

---

Dockerfile
app/main/controller/audio_similarity_controller.py
app/main/controller/image_similarity_controller.py
app/main/controller/video_similarity_controller.py
app/test/test_audio_similarity.py
app/test/test_image_similarity.py
production/Dockerfile

This doesn't get run in develop - and I don't remember why we even have different dockerfiles - but we need to remove chromaprint from the prod file.
Reference: CV2-4637
Not tested locally, for the above reason^
None

CV2-4637 remove chromaprint from production dockerfile build

---

app/main/controller/similarity_async_controller.py

Renaming namespace and variable to not step on other namespace
Reference: CV2-4997
Not tested locally but as is self-evident, this is ... very minor
None

CV2-4997 fix bad namespace

---

app/main/lib/shared_models/video_model.py

Small logging line for missing hash values as per discussion with @computermacgyver 
Reference: CV2-4790
NA
NA

CV2-4790 add error log for any empty hash value

---

app/main/controller/image_ocr_controller.py

Revert commits to 5413a6e6655d6a37683b70a38a49ce5c8fec08fe

Revert commits to 5413a6e6655d6a37683b70a38a49ce5c8fec08fe

---

app/main/lib/langid.py
app/test/test_langid.py

CV2-5412: no newlines in text for FastText

---

app/main/lib/elastic_crud.py
app/main/lib/media_crud.py
app/main/lib/text_similarity.py

Very minor tweak to remove some erroneous logs that were either mislabeled or unnecessary outside development context.
Reference: CV2-5050
Not Tested locally but expected to be.... obviously quite minimal.
None

CV2-5050 remove some old logs from development work

---

CODEOWNERS

update CODEOWNERS to include infrastructure team for changes involving deloyment and containers
As discussed on to align across services and policies

update CODEOWNERS to include infrastructure team

---

.github/workflows/ci-deploy-env.yml

upgrade deprecated github actions steps

update gha workflow step versions

---

.github/workflows/ci-tests.yaml

removes daily test run
References: CV2-6257

remove scheduled CI workflow
